language: perl
sudo: true

install:
  - sudo apt-get update
  - sudo apt-get install libedit-dev
  - perlbrew list
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"

script:
  - dzil test

env:
  - ALIEN_FORCE=1
  - ALIEN_FORCE=0
